# Site settings
title: Chloe Atchue-Mamlet
email: chloe793@gmail.com
description: "Chloe Atchue-Mamlet is a graphic design student and web enthusiast in Philadelphia, PA. This is her portfolio and blog."
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://chloeam.com" # the base hostname & protocol for your site
repo: https://github.com/chloeam/chloeam.github.io
google_analytics_code: UA-66523344-1

# Social media
twitter_username: chloe793
github_username:  chloeam
codepen_username: chloeam
linkedin_link: https://www.linkedin.com/pub/chloe-atchue-mamlet/ab/b74/6a0 #must provide whole url for linkedin
behance_username: chloeam
instagram_username: chloe793

# Build settings
markdown: kramdown
permalink: /blog/:title/
gems: [bourbon, neat, jekyll-sitemap]

collections:
  components:
    output: false
  colors:
    output: false

#navigation:
# - title: Portfolio
#   url: /index.html
# - title: Blog
#   url: /blog/
# - title: About
#   url: /about/
