# Site settings
title: Chloe Atchue-Mamlet
email: chloe793@gmail.com
description: > # this means to ignore newlines until next variable
  Portfolio and blog of Chloe Atchue-Mamlet
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site

# Social media
twitter_username: chloe793
github_username:  chloeam
codepen_username: chloeam
linkedin_link: https://www.linkedin.com/pub/chloe-atchue-mamlet/ab/b74/6a0 #must provide whole url for linkedin
behance_username: chloeam
instagram_username: chloe793

# Build settings
markdown: kramdown
permalink: pretty

#navigation:
# - title: Portfolio
#   url: /index.html
# - title: Blog
#   url: /blog/
# - title: About
#   url: /about/
